project_id = "cchhfgdowqlspxujfbrb"

[functions.invite-technician]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.push-test]
verify_jwt = false

[functions.create-quote-request]
verify_jwt = false
